trigger:
  - master

stages:
- stage: Build and Test
  jobs:
  - job: Build

    pool:
      vmImage: ubuntu-16.04

    steps:
      - task: Npm@1
        inputs:
          command: install
      - script: 'npm test'
        displayName: 'Run unit tests'
        continueOnError: true
      - task: PublishTestResults@2
        displayName: 'Publish Test Results'
        condition: succeededOrFailed()
        inputs:
          testResultsFiles: $(System.DefaultWorkingDirectory)/test-report.xml
      - task: PublishCodeCoverageResults@1
        displayName: 'Publish Code Coverage'
        condition: 'in(variables[''Agent.JobStatus''], ''Succeeded'')'
        inputs:
          codeCoverageTool: Cobertura
          summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/*coverage.xml'
          reportDirectory: $(System.DefaultWorkingDirectory)/coverage
      - task: ArchiveFiles@2
        displayName: 'Archive sources'
        inputs:
          rootFolderOrFile: $(Build.SourcesDirectory)
          includeRootFolder: false
      - task: CopyFiles@2
        displayName: 'Copy ARM templates'
        inputs:
          SourceFolder: deployment
          Contents: '*.json'
          TargetFolder: $(build.artifactstagingdirectory)/Templates
      - task: PublishBuildArtifacts@1
        displayName: 'Publish Artifact: drop'

- stage: Deploy to App Service
  jobs:
  - job: Deploy
  
    pool:
      name: Hosted VS2017
      demands:
      - msbuild
      - visualstudio
      - vstest

    steps:
    - task: DownloadBuildArtifacts@0
      inputs:
        buildType: 'current'
        artifactName: 'drop'
        downloadType: 'single'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: AzureResourceGroupDeployment@2
      inputs:
        azureSubscription: 'Northeast Azure TSP Subscription (4fa141ee-5558-4bf3-b338-27e747b044a5)'
        action: 'Create Or Update Resource Group'
        resourceGroupName: $(resourcegroup)
        location: 'East US 2'
        templateLocation: 'Linked artifact'
        csmFile: '$(System.DefaultWorkingDirectory)/_ContosoAir-CI/drop/Templates/azuredeploy.json'
        csmParametersFile: '$(System.DefaultWorkingDirectory)/_ContosoAir-CI/drop/Templates/azuredeploy.parameters.json'
        overrideParameters: '-p_environment contosoairkyle'
        deploymentMode: 'Incremental'

    - task: ARM Outputs@5
      inputs:
        ConnectedServiceNameSelector: 'ConnectedServiceNameARM'
        ConnectedServiceNameARM: 'Northeast Azure TSP Subscription (4fa141ee-5558-4bf3-b338-27e747b044a5)'
        resourceGroupName: $(resourcegroup)
        whenLastDeploymentIsFailed: 'fail'

    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Northeast Azure TSP Subscription (4fa141ee-5558-4bf3-b338-27e747b044a5)'
        appType: 'webApp'
        WebAppName: $(web)
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'